CREATE TABLE "users" (
    "id" uuid PRIMARY KEY,
    "created_at" TIMESTAMPTZ DEFAULT (NOW()),
    "dlsu_id" numeric(8) NOT NULL,
    "home_college" smallint NOT NULL
);

CREATE TABLE "colleges" (
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "acronym" text NOT NULL,
    "name" text
);

CREATE TABLE "course_schedules" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMPTZ DEFAULT (NOW()),
    "last_updated" TIMESTAMPTZ DEFAULT (NOW()),
    "class_number" smallint NOT NULL,
    "term" numeric(4) NOT NULL,
    "day" varchar(1) NOT NULL,
    "start_time" time,
    "end_time" time,
    "room" text
);

CREATE TABLE "courses" (
    "class_number" smallint NOT NULL,
    "term" numeric(4) NOT NULL,
    "course_code_id" smallint NOT NULL,
    "created_at" TIMESTAMPTZ DEFAULT (NOW()),
    "enrolled" smallint NOT NULL,
    "capacity" smallint NOT NULL,
    "last_updated" TIMESTAMPTZ DEFAULT (NOW()),
    "remarks" text,
    "section" text NOT NULL,
    "faculty_id" smallint,
    PRIMARY KEY ("class_number", "term")
);

CREATE TABLE "course_codes" (
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "course_code" varchar(7) NOT NULL,
    "created_at" TIMESTAMPTZ DEFAULT (NOW()),
    "fullName" text
);

CREATE TABLE "faculty" (
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMPTZ DEFAULT (NOW()),
    "full_name" text
);

ALTER TABLE
    "users"
ADD
    FOREIGN KEY ("home_college") REFERENCES "colleges" ("id");

ALTER TABLE
    "course_schedules"
ADD
    FOREIGN KEY ("class_number", "term") REFERENCES "courses" ("class_number", "term");

ALTER TABLE
    "courses"
ADD
    FOREIGN KEY ("course_code_id") REFERENCES "course_codes" ("id");

ALTER TABLE
    "courses"
ADD
    FOREIGN KEY ("faculty_id") REFERENCES "faculty" ("id");