CREATE TABLE "users" (
    "id" uuid PRIMARY KEY,
    "created_at" timestamp DEFAULT (NOW()),
    "dlsuid" numeric(8) NOT NULL,
    "homeCollege" smallint NOT NULL
);

CREATE TABLE "colleges" (
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "acronym" text NOT NULL,
    "name" text
);

CREATE TABLE "courseSchedules" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp DEFAULT (NOW()),
    "last_updated" timestamp DEFAULT (NOW()),
    "classNumber" smallint NOT NULL,
    "term" numeric(4) NOT NULL,
    "day" varchar(1) NOT NULL,
    "startTime" time,
    "endTime" time,
    "room" text
);

CREATE TABLE "courses" (
    "classNumber" smallint,
    "term" numeric(4),
    "courseCodeId" smallint NOT NULL,
    "created_at" timestamp DEFAULT (NOW()),
    "enrolled" smallint NOT NULL,
    "capacity" smallint NOT NULL,
    "last_updated" timestamp DEFAULT (NOW()),
    "remarks" text,
    "section" text NOT NULL,
    "facultyId" smallint,
    PRIMARY KEY ("classNumber", "term")
);

CREATE TABLE "courseCodes" (
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "courseCode" varchar(7) NOT NULL,
    "created_at" timestamp DEFAULT (NOW()),
    "fullName" text
);

CREATE TABLE "faculty" (
    "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp DEFAULT (NOW()),
    "fullName" text
);

ALTER TABLE
    "users"
ADD
    FOREIGN KEY ("homeCollege") REFERENCES "colleges" ("id");

ALTER TABLE
    "courseSchedules"
ADD
    FOREIGN KEY ("classNumber", "term") REFERENCES "courses" ("classNumber", "term");

ALTER TABLE
    "courses"
ADD
    FOREIGN KEY ("courseCodeId") REFERENCES "courseCodes" ("id");

ALTER TABLE
    "courses"
ADD
    FOREIGN KEY ("facultyId") REFERENCES "faculty" ("id");